<?php

$author      = 'Christopher Keers';
$description = 'Site Planning assignment for WDD 130.';
$keywords    = 'Site, Planning, WDD 130, BYUI, Assignment, Homework';
$title       = 'Site Planning - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Creating a Site Plan</h1>
            <p>
                Developing a site plan is a critical step in any web design process. Site plans help establish the purpose of a website by setting the voice, tone, and messaging of a website. Site plans include the overall look and feel of the website as well, this helps developers apply the vision (site plan) consistently across the entire site.
            </p>
            <p>
                Site plans come in many shapes, sizes, and levels of detail. Here is a list of common elements in a site plan:
            </p>
            <ul class="smaller">
                <li>
                    Statement of purpose and goals.
                </li>
                <li>
                    Definition of audience.
                </li>
                <li>
                    Persona and scenario documents: Who will use the site and how will they use it?
                </li>
                <li>
                    A Style guide:
                    <ul>
                        <li>
                            Branding information for example how to use the branding for the site correctly on and off site.
                        </li>
                        <li>
                            Typography choices and justification.
                        </li>
                        <li>
                            Color palette.
                        </li>
                        <li>
                            Specific styling of elements on the site such as headings, lists, paragraphs, forms, links, buttons, etc.
                        </li>
                        <li>
                            A sitemap.
                        </li>
                        <li>
                            Wireframes showing general layout and content for major pages.
                        </li>
                    </ul>
                </li>
            </ul>
        </main>
{{FOOTER}}
    </div>
</body>
</html>