<?php

$author      = 'Christopher Keers';
$description = 'Site Planning assignment for WDD 130.';
$keywords    = 'Site, Planning, WDD 130, BYUI, Assignment, Homework';
$title       = 'Site Planning - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Creating a Site Plan</h1>
            <p>
                Developing a site plan is a critical step in any web design process. Site plans help establish the purpose of a website by setting the voice, tone, and messaging of a website. Site plans include the overall look and feel of the website as well, this helps developers apply the vision (site plan) consistently across the entire site.
            </p>
            <p>
                Site plans come in many shapes, sizes, and levels of detail. Here is a list of common elements in a site plan:
            </p>
            <ul class="smaller">
                <li>
                    Statement of purpose and goals.
                </li>
                <li>
                    Definition of audience.
                </li>
                <li>
                    Persona and scenario documents: Who will use the site and how will they use it?
                </li>
                <li>
                    A Style guide:
                    <ul>
                        <li>
                            Branding information for example how to use the branding for the site correctly on and off site.
                        </li>
                        <li>
                            Typography choices and justification.
                        </li>
                        <li>
                            Color palette.
                        </li>
                        <li>
                            Specific styling of elements on the site such as headings, lists, paragraphs, forms, links, buttons, etc.
                        </li>
                        <li>
                            A sitemap.
                        </li>
                        <li>
                            Wireframes showing general layout and content for major pages.
                        </li>
                    </ul>
                </li>
            </ul>
            <h2>The Family Search Example</h2>
            <blockquote cite="https://link-to-source.com">
                <p>
                    The Church of Jesus Christ of Latter-day Saints provides FamilySearch free of charge to everyone, regardless of tradition, culture, or religious affiliation... We help people discover their family’s history through our website, mobile apps, and in-person help at over 5,000 local family history centers.
                </p>
                <cite>
                    Family Search
                </cite>
            </blockquote>
            <p>
                FamilySearch has an <a href="https://www.familysearch.org/frontier/styleguide/" target="_blank">in depth style guide viewable by anyone</a>; please take some time now to review it. Did you notice how many colors they use! As you browse around the actual site do you think it's too many colors or does it work? Notice that they also have a section about font sizes, paragraphs, and headline styling, but they never really mention which fonts they use.
            </p>
            <p>
                Take a moment and think about the purpose and audience of the Family Search site. Does the site accomplish the purpose well and cater to its audience? What do you like or dislike about this site? Now take these thoughts and apply them to all the planning you do for your final project website.
            </p>
            <h2>Assignment</h2>
            <ol>
                <li>
                    Determine a color scheme for your final project site; you may come up with more colors than this exercise has you use.
                </li>
                <li>
                    Edit the <code>replace.css</code> file with your new colors. Be careful what you replace! I may have made some CSS mistakes that you might have to fix. <a href="https://github.com/caboodle-tech/wdd-130-project/tree/main/exercises/week-6/site-plan" target="_blank">I am refering to these files</a>.
                </li>
                <li>
                    Now visit <a href="https://fonts.google.com/" target_blank">Google Fonts</a> and choose two fonts that you want on your final project site. One will be for general text and the other will be used for headers and headlines. You will need to add the embed link into the HTML page (in the head) so you can use the fonts, then replace the font family in the appropriate spots in your css file.
                </li>
                <li>
                    Your almost done. Make sure to commit and push your changes to your GitHub repository. I will grade them in a later week. Don't forget to do the dark mode challenge. This is the same exact assignment but with dark colors. The files are in the challenge directory not the exercise directory.
                </li>
            </ol>
        </main>
{{FOOTER}}
    </div>
</body>
</html>