<?php

$author      = 'Christopher Keers';
$description = 'Grid Practice assignment for WDD 130.';
$keywords    = 'Grid, Style, CSS, Design, Principles, Site, Planning, WDD 130, BYUI, Assignment, Homework';
$title       = 'Grid Practice - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Grid Practice</h1>
            <p>
                Well you have already started doing some work on your final project website, next week marks the transition to full time development. This assignment is meant to be a capstone to your CSS grid layout knowledge. It will help you use grid appropriately in your final project website.
            </p>
            <h2>Assignment:</h2>
            <ol>
                <li>
                    Please visit <a href="https://cssgridgarden.com/" target="_blank">Grid Garden</a> and complete all 28 levels of the game.
                </li>
                <li>
                    <h2>Grading</h2>
                    <p>
                        Please report that you completed all 28 levels of the CSS Grid Garden game in the Canvas quiz for this assignment.
                    </p>
                </li>
            </ol>
        </main>
{{FOOTER}}
    </div>
</body>
</html>