<?php

$author      = 'Christopher Keers';
$description = '';
$keywords    = '';
$title       = 'Web Fundamentals - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <main>
            <h1>Home Page</h1>
            <p>
                No content yet.
            </p>
            <h2>Week 1</h2>
            <ul class="smaller">
                <li>
                    About Me Introduction (Canvas)
                </li>
                <li>
                    Introduction to HTML / Vocabulary
                </li>
                <li>
                    Introduction to CSS / Vocabulary
                </li>
                <li>
                    Software & Account Setup
                </li>
            </ul>
            <h2>Week 2</h2>
            <ul class="smaller">
                <li>
                    Introduction to Glitch
                </li>
                <li>
                    Introduction to Wire Framing
                </li>
                <li>
                    About Me HTML on Glitch
                </li>
                <li>
                    About Me CSS on Glitch
                </li>
            </ul>
            <h2>Week 3</h2>
            <ul class="smaller">
                <li>
                    <a href="https://youtu.be/y9gLCKRox2g" target="_blank">Introduction to LESS</a>
                </li>
                <li>
                    About Me LESS on Glitch
                </li>
                <li>
                    Weeks 1 - 3 Recap
                </li>
            </ul>
            <h2>Week 4</h2>
            <ul class="smaller">
                <li>
                    Introduction to git
                </li>
                <li>
                    Introduction to GitHub
                </li>
                <li>
                    Clone Your First GitHub Repository
                </li>
            </ul>
            <h2>Week 5</h2>
            <ul class="smaller">
                <li>
                    <a href="week-5/flexbox-layout.html">Introduction to CSS Flexbox Layouts</a>
                </li>
                <li>
                    <a href="week-5/grid-layout.html">Introduction to CSS Grid Layouts</a> 
                </li>
                <li>
                    <a href="week-5/flexbox-vs-grid.html">Comparing CSS Flexbox & Grid</a>
                </li>
            </ul>
            <h2>Week 6</h2>
            <p>
                This week does not focus on learning new code or style concepts and has fewer assignments than normal. You should use this additional time to catch up on missing work, complete challenge assignments, and plan ahead for your final project. Please take the planning and writing portion of your site plans seriously. If you have extra time this week consider preparing for your mid-terms in other classes.
            </p>
            <ul class="smaller">
                <li>
                    <a href="week-6/elevator-pitch.html">Creating an Elevator Pitch</a>
                </li>
                <li>
                    <a href="week-6/site-planning.html">Site Planning</a>
                </li>
                <li>
                    <strong>Challenges</strong>
                    <ul>
                        <li>
                        <a href="week-6/site-planning.html">Dark Mode Site Plan</a>
                        <p>
                            This is the same assignment as the Site Planning assignment. Just make sure to use dark colors. The files for this assignment are in the <a href="https://github.com/caboodle-tech/wdd-130-project/tree/main/challenges/week-6/dark-mode-site-plan" target="_blank">challenge directory</a> not the exercise directory.
                        </p>
                        </li>
                    </ul>
                </li>
            </ul>
            <h2>Week 7</h2>
            <ul class="smaller">
                <li>
                    <a href="week-7/design-principles.html">Design Principles</a>
                </li>
                <li>
                    <a href="week-7/subpages-and-wireframes.html">Subpages and Wireframes</a>
                </li>
            </ul>
        </main>
{{FOOTER}}
    </div>
</body>
</html>