<?php

$author      = 'Christopher Keers';
$description = '';
$keywords    = '';
$title       = 'Web Fundamentals - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <main>
            <h1>Home Page</h1>
            <p>
                No content yet.
            </p>
            <h2>Week 1</h2>
            <ul class="smaller">
                <li>
                    About Me Introduction (Canvas)
                </li>
                <li>
                    Introduction to HTML / Vocabulary
                </li>
                <li>
                    Introduction to CSS / Vocabulary
                </li>
                <li>
                    Software & Account Setup
                </li>
            </ul>
            <h2>Week 2</h2>
            <ul class="smaller">
                <li>
                    Introduction to Glitch
                </li>
                <li>
                    Introduction to Wire Framing
                </li>
                <li>
                    About Me HTML on Glitch
                </li>
                <li>
                    About Me CSS on Glitch
                </li>
            </ul>
            <h2>Week 3</h2>
            <ul class="smaller">
                <li>
                    Introduction to LESS
                </li>
                <li>
                    About Me LESS on Glitch
                </li>
                <li>
                    Weeks 1 - 3 Recap
                </li>
            </ul>
            <h2>Week 4</h2>
            <ul class="smaller">
                <li>
                    Introduction to git
                </li>
                <li>
                    Introduction to GitHub
                </li>
                <li>
                    Clone Your First GitHub Repository
                </li>
            </ul>
            <h2>Week 5</h2>
            <ul class="smaller">
                <li>
                    <a href="week-5/elevator-pitch.html">Creating an Elevator Pitch</a>
                </li>
                <li>
                    Introduction to CSS Flexbox Layouts
                </li>
                <li>
                    <a href="week-5/grid-layout.html">Introduction to CSS Grid Layouts</a> 
                </li>
                <li>
                    <a href="week-5/flexbox-vs-grid.html">Comparing CSS Flexbox & Grid</a>
                </li>
            </ul>
        </main>
{{FOOTER}}
    </div>
</body>
</html>