<?php

$author      = 'Christopher Keers';
$description = 'Introduction to CSS flexbox layouts. Assignment for WDD 130.';
$keywords    = 'CSS, Flexbox, Grid, WDD 130, BYUI, Assignment, Homework';
$title       = 'Intro to Flexbox Layout - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Introduction to CSS Flexbox Layouts</h1>
            <p>
                This assignment will not be available this semester. Below is a list of resources I plan to use for this assignment, you might want to review them for this semester:
            </p>
            <ul>
                <li>
                    <a href="https://demos.scotch.io/visual-guide-to-css3-flexbox-flexbox-playground/demos/" target="_blank">Flex Playground</a>
                </li>
                <li>
                    <a href="https://www.w3schools.com/css/css3_flexbox.asp" target="_blank">W3Schools Flexbox</a>
                </li>
            </ul>
        </main>
{{FOOTER}}
    </div>
</body>
</html>