<?php

$author      = 'Christopher Keers';
$description = 'Comparing CSS Flexbox & Grid assignment for WDD 130.';
$keywords    = 'CSS, Flexbox, Grid, WDD 130, BYUI, Assignment, Homework';
$title       = 'WDD 130 - Comparing CSS Flexbox & Grid';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Comparing CSS Flexbox and Grid</h1>
            <p>
                You should have completed the <a href="" target="_blank">Introduction to CSS Flexbox Layouts</a> and <a href="" target="_blank">Introduction to CSS Grid Layouts</a> assignments before starting this assignment. 
            </p>
            <h2>Assignment:</h2>
            <ol>
                <li>
                    <h2>Review Materials</h2>
                    <p>
                        In this assignment we want to dive further into what flexbox and grid are an what they are not. Below are the links to the Mozilla Developers Network Web Docs (MDN Web Docs) pages for flexbox and grid. Please give these a quick review, you do not need to read everything here.
                    </p>
                    <ul>
                        <li>
                            <a href="https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox" target="_blank">Flexbox Layout</a>
                        </li>
                        <li>
                        <a href="https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids" target="_blank">Grid Layout</a>
                        </li>
                    </ul>
                    <p>
                        The MDN is a valuable resource to learn about web technologies and will help you if you choose to go into software development. The MDN defines their purpose as:
                    </p>
                    <blockquote cite="https://developer.mozilla.org/en-US/docs/MDN/About">    
                        MDN Web Docs (previously known as MDN — the Mozilla Developer Network) is an evolving learning platform for Web technologies and the software that powers the Web, including:
                        <ul>
                            <li>
                                Web standards such as <a href="/en-US/docs/CSS" title="/en-US/docs/CSS">CSS</a>, <a href="/en-US/docs/HTML" title="/en-US/docs/HTML">HTML</a>, and <a href="/en-US/docs/JavaScript" title="/en-US/docs/JavaScript">JavaScript</a>
                            </li>
                            <li>
                                <a href="/en-US/docs/Apps" title="/en-US/docs/Apps">Open Web app development</a>
                            </li>
                            <li>
                                <a href="/en-US/docs/Add-ons" title="/en-US/docs/Add-ons">Firefox add-on development</a>
                            </li>
                        </ul>
                    </blockquote>
                </li>
                <li>
                    <h2>Read the Resource</h2>
                    <p>
                        CSS-Tricks is an awesome tech blog that started its life posting about CSS tricks for cross-browser design. In the past various web browsers often displayed the same web designs in very different ways. Developers and designers had to add extra code to insure their designs looked and operated the same cross-browser. This problem, well substantially reduced today, still exists. The CSS-Tricks website has evolved to cover many topics and I would recommend them to you as another resource for software development and web design.
                    </p>
                    <p>
                        Please read CSS-Tricks article <a href="https://css-tricks.com/css-grid-replace-flexbox/" target="_blank">Does CSS Grid Replace Flexbox?</a> which helps compare and contrast flexbox and grid.
                    </p>
                </li>
                <li>
                    <h2>Report</h2>
                    <p>
                        Please complete the quiz in Canvas to mark yourself as completed for this assignment.
                    </p>
                    <div class="rubric">
                        <h2>Grading (? pts)</h2>
                        <p>
                            This activity will be graded using the following rubric:
                        </p>
                        <ul>
                            Complete the associated quiz in canvas to report on completing this assignment. (? pts)
                        </li>
                        </ul>
                    </div>
                </li>
        </main>
{{FOOTER}}
    </div>
</body>
</html>