<?php

$author      = 'Christopher Keers';
$description = 'Introduction to CSS grid layouts. Assignment for WDD 130.';
$keywords    = 'CSS, Flexbox, Grid, WDD 130, BYUI, Assignment, Homework';
$title       = 'Intro to Grid Layout - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Introduction to CSS Grid Layouts</h1>
            <p>
                In this assignment we will explore the newest method for web layouts: grid. As it's name implies CSS grid treats the web page as a grid and allows you to specify with CSS how elements should stretch and span to fill this grid. You can even leave grid squares empty if you choose.
            </p>
            <h2>Dmonstration Video:</h2>
            <p>
                This assignment has an accompanying demonstration video. Watching the video before starting this assignment may be helpful. Some students may find pausing the video and completing the assignment in conjunction to be most beneficial. Please follow whichever learning style is best for you:
            </p>
            <p>
                <strong>Coming Soon!!!</strong>
            </p>
            <a href="https://youtu.be/NpEaa2P7qZI" target="_blank" data-video="YouTube">Video Placeholder</a>
            <h2>Assignment:</h2>
            
        </main>
{{FOOTER}}
    </div>
</body>
</html>