<?php

$author      = 'Christopher Keers';
$description = 'Design Principles assignment for WDD 130.';
$keywords    = 'Design, Principles, Site, Planning, WDD 130, BYUI, Assignment, Homework';
$title       = 'Design Principles - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Design Principles</h1>
            <p>
                In this activity we will introduce you to some basic design principles. These principles are core to design and can be applied to any kind of design work you might find yourself asked to do in the future. As you visit websites, view posters, read magazines, watch movies, and so on over the next few days, please look out for examples of these principles being used. If you watch for them, you will start seeing examples of these design principles everywhere.
            </p>
            <h2>Assignment:</h2>
            <ol>
                <li>
                    Please watch the following video:
                    <a href="https://youtu.be/a5KYlHNKQB8" target="_blank" data-video="YouTube">
                        Beginning Graphic Design: Layout & Composition
                    </a>
                </li>
                <li>
                    Please review and consider keeping a copy of the following info-graphics:
                    <ul>
                        <li>
                            <a href="https://byui-cit.github.io/wdd130/images/colortheory_1440.jpg" target="_blank">Color Theory</a>
                        </li>
                        <li>
                            <a href="https://byui-cit.github.io/wdd130/images/ElementsofDesign_Grey_1440.jpg" target="_blank">Elements of Design</a>
                        </li>
                        <li>
                            <a href="https://byui-cit.github.io/wdd130/images/Principles-of-Design-Grey-1440px.jpg" target="_blank">Principles of Design</a>
                        </li>
                    </ul>
                </li>
            </ol>
        </main>
{{FOOTER}}
    </div>
</body>
</html>