<?php

$author      = 'Christopher Keers';
$description = 'Subpages and Wireframes assignment for WDD 130.';
$keywords    = 'Wirefrmae, Design, Principles, Site, Planning, WDD 130, BYUI, Assignment, Homework';
$title       = 'Subpages and Wireframes - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Subpages and Wireframes</h1>
            <p>
                In this assignment we will we work on developing content for your final project website. We will also cover additional design principles, this time focusing on website images. You will also be asked to stretch your Web Designer (User Interface Designer) skills by creating wire frames for the content and subpages you have planned.
            </p>
            <h2>Assignment:</h2>
            <ol>
                <li>
                    <h2>Brainstorm</h2>
                    <p>
                        Last week you were asked to decide on a topic for your personal website and create an elevator pitch <i>selling</i> your idea. You should also have thought about your intended audience. This week begin by reviewing your pitch and intended audience, then think about three topics your website will cover. Write those 3 topics down.
                    </p>
                </li>
                <li>
                    <h2>Write</h2>
                    <p>
                        With your topics and audience in mind, please write at least 600 words on your website idea providing text content that your audience may want to read or get from your website. You can just free-write any pertinent information about your website idea following good sentence structure and thought processes. This content will be a rough draft in this week but will be refined in subsequent weeks to become what the users will be reading on your website. More content is often better than less when designing a website. You may consider answering some or all of the following questions about your website idea:
                    </p>
                    <ul>
                        <li>
                            Why will people come to your site?
                        </li>
                        <li>
                            What questions will your visitors expect your site to answer for them?
                        </li>
                        <li>
                            What types of activities will visitors want to complete on your site?
                        </li>
                        <li>
                            What information is necessary to complete any actions your site offers?
                        </li>
                        <li>
                            Why will your visitors come to your site instead of another to get this information or complete the actions?
                        </li>
                    </ul>
                </li>
                <li>
                    <h2>Organize</h2>
                    <p>
                        With your topics and audience in mind, please write at least 600 words on your website idea providing text content that your audience may want to read or get from your website. You can just free-write any pertinent information about your website idea following good sentence structure and thought processes. This content will be a rough draft in this week but will be refined in subsequent weeks to become what the users will be reading on your website. More content is often better than less when designing a website. You may consider answering some or all of the following questions about your website idea:
                    </p>
                    <ul>
                        <li>
                            Why will people come to your site?
                        </li>
                        <li>
                            What questions will your visitors expect your site to answer for them?
                        </li>
                        <li>
                            What types of activities will visitors want to complete on your site?
                        </li>
                        <li>
                            What information is necessary to complete any actions your site offers?
                        </li>
                        <li>
                            Why will your visitors come to your site instead of another to get this information or complete the actions?
                        </li>
                    </ul>
                </li>
                <li>
                    <h2>Images</h2>
                    <p>
                        Images often play a very large role in how we view and feel about websites. You should put some thought into images that could go with your content. These images should enhance the content you generated above. To begin watch this short video:
                    </p>
                    <a href="https://youtu.be/MELKuexR3sQ" target="_blank" data-video="YouTube">
                        Beginning Graphic Design: Images by GCFLearnFree.org
                    </a>
                    <p>
                        For each of your pages find 2 or 3 images that could be used to enhance the content of that page. These can be images that you create yourself or images that you have found. If you find the images online make sure to honor their copyright. Do not use images that are not stated as free to use. Here are a couple of good sources for good, high quality, free stock images and icons:
                        <ul>
                            <li>
                                <a href="https://unsplash.com/" target="_blank">Uplash</a>
                            </li>
                            <li>
                                <a href="https://www.canva.com/photos/people/" target="_blank">Canva</a>
                            </li>
                            <li>
                                <a href="https://www.freepik.com/" target="_blank">Freepik</a>
                            </li>
                            <li>
                                <a href="https://www.smashingmagazine.com/category/freebies" target="_blank">Smashing Magazine List of Free Icons</a>
                            </li>
                        </ul>
                    </p>
                    <p>
                        Make sure to <a href="https://byui-cit.github.io/wdd130/resources/optimizing-images.html" target="_blank">optimize your images</a>!
                    </p>
                </li>
                <li>
                    <h2>Grading</h2>
                    <p>
                        You will prove you completed this assignment in the coming week(s), make sure you have this material ready when I ask for it. You may save it anywhere you see fit but consider adding it to your GitHub repository for practice.
                    </p>
                </li>
            </ol>
        </main>
{{FOOTER}}
    </div>
</body>
</html>