<footer>
    <!-- BYUI -->
    <a rel="author" href="https://www.byui.edu/computer-information-technology" target="_blank"><img alt="Creative Commons License" class="byui-img" src="{{PATH}}assets/byui-logo.jpg"></a>
    <!-- CC BY-NC-SA -->
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank"><img alt="Creative Commons License" class="cc-img" src="{{PATH}}assets/CC-BY-NC-SA.svg.png"></a>
    <!-- Legal text -->
    <span class="line-break"></span>
    This work was created by the Computer Information Technology Department at Brigham Young University Idaho and is licensed under a <a rel="license" href="https://github.com/caboodle-tech/byui/blob/main/LICENSE-CC-BY-NC-SA" target="_blank">Creative Commons BY-NC-SA 4.0 License</a>. The source code for this website is licensed under the <a rel="license" href="https://github.com/caboodle-tech/byui/blob/main/LICENSE" target="_blank">MIT License</a> unless noted otherwise.
</footer>