<?php

$author      = 'Christopher Keers';
$description = 'Contact Page Style assignment for WDD 130.';
$keywords    = 'Contact, Style, Forms, Design, Principles, Site, Planning, WDD 130, BYUI, Assignment, Homework';
$title       = 'Contact Style - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Contact Style</h1>
            <p>
                Add styles to compete the contact page and publish it to your GitHub website.
            </p>
            <h2>Assignment:</h2>
            <ol>
                <li>
                    Coming later.
                </li>
            </ol>
        </main>
{{FOOTER}}
    </div>
</body>
</html>