<?php

$author      = 'Christopher Keers';
$description = 'Contact Us Page assignment for WDD 130.';
$keywords    = 'Contact Us, Forms, Design, Principles, Site, Planning, WDD 130, BYUI, Assignment, Homework';
$title       = 'Contact Us Page - WDD 130';

?>
{{HEAD}}
<body>
    <div id="page">
        <header>
            <div id="course-title">
                Web Fundamentals
            </div>
            <div id="course-code">
                WDD 130
            </div>
        </header>
        <div id="go-back">
            <a href="../">&#10554; Go Back</a>
        </div>
        <main>
            <h1>Contact Us Page</h1>
            <p>
                In this assignment we will start work on the contact page for your final project website. Our goal is to get the content and HTML structure in place first. Later in the week we will add styles to compete the page and publish it to your GitHub website.
            </p>
            <h2>Assignment:</h2>
            <ol>
                <li>
                    <h2>Create the Page Content</h2>
                    <p>
                        A contact us page can be as simple as a contact form or as advanced as an interactive question and answer application. We will stick with a simple contact us page that invites the user to view certain pages of our site for the information they might be looking for. If they can not find what they are looking for we would encourage them to contact us.
                    </p>
                    <p>
                        Please write between 150 - 450 words inviting users to view your sub-pages first. At the end of this content include a message that addresses users who did not find the information they were looking for or want to contact you about something different. This message should encourage them to reach out by using the contact us form.
                    </p>
                </li>
                <li>
                    <h2>Create the Form</h2>
                    <p>
                        Now that we have the content for the page done you should make the HTML for the contact form. Your form should include an input field for the users name and subject, a textarea for their message, and a single button to submit the form.
                    </p>
                </li>
                <li>
                    <h2>Grading</h2>
                    <p>
                        You will prove you completed this assignment in the coming week(s), make sure you have this material ready when I ask for it. You may save it anywhere you see fit but consider adding it to your GitHub repository for practice.
                    </p>
                </li>
            </ol>
        </main>
{{FOOTER}}
    </div>
</body>
</html>